package com.dinfo.tp3.classes;

// Generated Dec 6, 2014 1:39:51 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BiArticles generated by hbm2java
 */
public class BiArticles implements java.io.Serializable {

	private String isbn;
	private BiTypearticles biTypearticles;
	private String titre;
	private String resume;
	private BigDecimal prixUnitaire;
	private char indicateurEnCommande;
	private short quantiteEnCommande;
	private Date dateParution;
	private int maisonEditionId;
	private String langue;
	private int ageMinimum;
	private Set biReservations = new HashSet(0);
	private Set biAuteurses = new HashSet(0);
	private Set biCopiesarticleses = new HashSet(0);

	public BiArticles() {
	}

	public BiArticles(String isbn, BiTypearticles biTypearticles, String titre,
			String resume, BigDecimal prixUnitaire, char indicateurEnCommande,
			short quantiteEnCommande, Date dateParution, int maisonEditionId,
			String langue, int ageMinimum) {
		this.isbn = isbn;
		this.biTypearticles = biTypearticles;
		this.titre = titre;
		this.resume = resume;
		this.prixUnitaire = prixUnitaire;
		this.indicateurEnCommande = indicateurEnCommande;
		this.quantiteEnCommande = quantiteEnCommande;
		this.dateParution = dateParution;
		this.maisonEditionId = maisonEditionId;
		this.langue = langue;
		this.ageMinimum = ageMinimum;
	}

	public BiArticles(String isbn, BiTypearticles biTypearticles, String titre,
			String resume, BigDecimal prixUnitaire, char indicateurEnCommande,
			short quantiteEnCommande, Date dateParution, int maisonEditionId,
			String langue, int ageMinimum, Set biReservations, Set biAuteurses,
			Set biCopiesarticleses) {
		this.isbn = isbn;
		this.biTypearticles = biTypearticles;
		this.titre = titre;
		this.resume = resume;
		this.prixUnitaire = prixUnitaire;
		this.indicateurEnCommande = indicateurEnCommande;
		this.quantiteEnCommande = quantiteEnCommande;
		this.dateParution = dateParution;
		this.maisonEditionId = maisonEditionId;
		this.langue = langue;
		this.ageMinimum = ageMinimum;
		this.biReservations = biReservations;
		this.biAuteurses = biAuteurses;
		this.biCopiesarticleses = biCopiesarticleses;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public BiTypearticles getBiTypearticles() {
		return this.biTypearticles;
	}

	public void setBiTypearticles(BiTypearticles biTypearticles) {
		this.biTypearticles = biTypearticles;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getResume() {
		return this.resume;
	}

	public void setResume(String resume) {
		this.resume = resume;
	}

	public BigDecimal getPrixUnitaire() {
		return this.prixUnitaire;
	}

	public void setPrixUnitaire(BigDecimal prixUnitaire) {
		this.prixUnitaire = prixUnitaire;
	}

	public char getIndicateurEnCommande() {
		return this.indicateurEnCommande;
	}

	public void setIndicateurEnCommande(char indicateurEnCommande) {
		this.indicateurEnCommande = indicateurEnCommande;
	}

	public short getQuantiteEnCommande() {
		return this.quantiteEnCommande;
	}

	public void setQuantiteEnCommande(short quantiteEnCommande) {
		this.quantiteEnCommande = quantiteEnCommande;
	}

	public Date getDateParution() {
		return this.dateParution;
	}

	public void setDateParution(Date dateParution) {
		this.dateParution = dateParution;
	}

	public int getMaisonEditionId() {
		return this.maisonEditionId;
	}

	public void setMaisonEditionId(int maisonEditionId) {
		this.maisonEditionId = maisonEditionId;
	}

	public String getLangue() {
		return this.langue;
	}

	public void setLangue(String langue) {
		this.langue = langue;
	}

	public int getAgeMinimum() {
		return this.ageMinimum;
	}

	public void setAgeMinimum(int ageMinimum) {
		this.ageMinimum = ageMinimum;
	}

	public Set getBiReservations() {
		return this.biReservations;
	}

	public void setBiReservations(Set biReservations) {
		this.biReservations = biReservations;
	}

	public Set getBiAuteurses() {
		return this.biAuteurses;
	}

	public void setBiAuteurses(Set biAuteurses) {
		this.biAuteurses = biAuteurses;
	}

	public Set getBiCopiesarticleses() {
		return this.biCopiesarticleses;
	}

	public void setBiCopiesarticleses(Set biCopiesarticleses) {
		this.biCopiesarticleses = biCopiesarticleses;
	}

}
