package com.dinfo.tp3.classes;

// Generated Dec 6, 2014 1:39:51 PM by Hibernate Tools 4.3.1

/**
 * BiMaisonseditions generated by hbm2java
 */
public class BiMaisonseditions implements java.io.Serializable {

	private long maisonEditionId;
	private BiProvinces biProvinces;
	private String nom;
	private String adresse;
	private String ville;
	private String cdPostal;
	private String pays;
	private String noTel;
	private String noFax;
	private String email;
	private String siteInternet;
	private String contact;

	public BiMaisonseditions() {
	}

	public BiMaisonseditions(long maisonEditionId, BiProvinces biProvinces,
			String nom, String adresse, String ville, String cdPostal,
			String pays, String noTel, String email) {
		this.maisonEditionId = maisonEditionId;
		this.biProvinces = biProvinces;
		this.nom = nom;
		this.adresse = adresse;
		this.ville = ville;
		this.cdPostal = cdPostal;
		this.pays = pays;
		this.noTel = noTel;
		this.email = email;
	}

	public BiMaisonseditions(long maisonEditionId, BiProvinces biProvinces,
			String nom, String adresse, String ville, String cdPostal,
			String pays, String noTel, String noFax, String email,
			String siteInternet, String contact) {
		this.maisonEditionId = maisonEditionId;
		this.biProvinces = biProvinces;
		this.nom = nom;
		this.adresse = adresse;
		this.ville = ville;
		this.cdPostal = cdPostal;
		this.pays = pays;
		this.noTel = noTel;
		this.noFax = noFax;
		this.email = email;
		this.siteInternet = siteInternet;
		this.contact = contact;
	}

	public long getMaisonEditionId() {
		return this.maisonEditionId;
	}

	public void setMaisonEditionId(long maisonEditionId) {
		this.maisonEditionId = maisonEditionId;
	}

	public BiProvinces getBiProvinces() {
		return this.biProvinces;
	}

	public void setBiProvinces(BiProvinces biProvinces) {
		this.biProvinces = biProvinces;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public String getCdPostal() {
		return this.cdPostal;
	}

	public void setCdPostal(String cdPostal) {
		this.cdPostal = cdPostal;
	}

	public String getPays() {
		return this.pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	public String getNoTel() {
		return this.noTel;
	}

	public void setNoTel(String noTel) {
		this.noTel = noTel;
	}

	public String getNoFax() {
		return this.noFax;
	}

	public void setNoFax(String noFax) {
		this.noFax = noFax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSiteInternet() {
		return this.siteInternet;
	}

	public void setSiteInternet(String siteInternet) {
		this.siteInternet = siteInternet;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

}
