package com.dinfo.tp3.classes;

// Generated Dec 6, 2014 1:39:51 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * BiModespaiements generated by hbm2java
 */
public class BiModespaiements implements java.io.Serializable {

	private String modePaiementCd;
	private String cdDescFr;
	private String cdDescEn;
	private Set biVenteses = new HashSet(0);
	private Set biEmpruntses = new HashSet(0);

	public BiModespaiements() {
	}

	public BiModespaiements(String modePaiementCd, String cdDescFr,
			String cdDescEn) {
		this.modePaiementCd = modePaiementCd;
		this.cdDescFr = cdDescFr;
		this.cdDescEn = cdDescEn;
	}

	public BiModespaiements(String modePaiementCd, String cdDescFr,
			String cdDescEn, Set biVenteses, Set biEmpruntses) {
		this.modePaiementCd = modePaiementCd;
		this.cdDescFr = cdDescFr;
		this.cdDescEn = cdDescEn;
		this.biVenteses = biVenteses;
		this.biEmpruntses = biEmpruntses;
	}

	public String getModePaiementCd() {
		return this.modePaiementCd;
	}

	public void setModePaiementCd(String modePaiementCd) {
		this.modePaiementCd = modePaiementCd;
	}

	public String getCdDescFr() {
		return this.cdDescFr;
	}

	public void setCdDescFr(String cdDescFr) {
		this.cdDescFr = cdDescFr;
	}

	public String getCdDescEn() {
		return this.cdDescEn;
	}

	public void setCdDescEn(String cdDescEn) {
		this.cdDescEn = cdDescEn;
	}

	public Set getBiVenteses() {
		return this.biVenteses;
	}

	public void setBiVenteses(Set biVenteses) {
		this.biVenteses = biVenteses;
	}

	public Set getBiEmpruntses() {
		return this.biEmpruntses;
	}

	public void setBiEmpruntses(Set biEmpruntses) {
		this.biEmpruntses = biEmpruntses;
	}

}
