package com.dinfo.tp3.classes;

// Generated Dec 6, 2014 1:39:51 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * BiReservation generated by hbm2java
 */
public class BiReservation implements java.io.Serializable {

	private long idReservation;
	private BiArticles biArticles;
	private BiMembres biMembres;
	private Date dateReservation;

	public BiReservation() {
	}

	public BiReservation(long idReservation, BiArticles biArticles,
			BiMembres biMembres, Date dateReservation) {
		this.idReservation = idReservation;
		this.biArticles = biArticles;
		this.biMembres = biMembres;
		this.dateReservation = dateReservation;
	}

	public long getIdReservation() {
		return this.idReservation;
	}

	public void setIdReservation(long idReservation) {
		this.idReservation = idReservation;
	}

	public BiArticles getBiArticles() {
		return this.biArticles;
	}

	public void setBiArticles(BiArticles biArticles) {
		this.biArticles = biArticles;
	}

	public BiMembres getBiMembres() {
		return this.biMembres;
	}

	public void setBiMembres(BiMembres biMembres) {
		this.biMembres = biMembres;
	}

	public Date getDateReservation() {
		return this.dateReservation;
	}

	public void setDateReservation(Date dateReservation) {
		this.dateReservation = dateReservation;
	}

}
